music_app/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
end

music_app/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  def self.generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end


end

music_app/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  #current_user, #logged_in?, #log_in_user!
  def log_in_user!(user)
    # debugger

    session[:session_token] = user.reset_session_token!
    #do i need to redicrect?
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!@current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end


end

music_app/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_no_user!, only: i(create) What is this?

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    debugger
    if user.nil?

      flash.now[:errors] = ['Invalid email and/or password']
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user) #correct? do I have to add show to UsersController
    # if user
    #   log_in_user!(user)
    #   redirect_to user_url(user) #correct? do I have to add show to UsersController
    # else
    #   flash.now[:errors] = ['Invalid email and/or password']
    #   render :new
    end
  end

  def destroy
  end

  def new
    render :new
  end


end

music_app/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :require_no_user!


  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end


  ##### redirect_to question
  def show
    # debugger
    render :show
  end
  # do i have to add this routes then?

  private

  def user_params
    params.require(:user).permit(:email, :password) #does order matter?
  end

end

music_app/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

music_app/music_app/app/views/users/new.html.erb
<h1 class='page-header'>Sign Up</h1>

<a class='button' href=<%= new_session_url %> >Go to Sign-in</a>

<form class="form" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <p>
    <label for="new-user-email">Email</label>
    <input id="new-user-email" type="text" name="user[email]">
  </p>

  <p>
    <label for="new-user-password">Password</label>
    <input id="new-user-password" type="password" name="user[password]">
  </p>

  <input type="submit" value="Submit">
</form>

music_app/music_app/app/views/users/show.html.erb
<h1 class='page-header'>User 1</h1>
<!-- <a class = 'button' href=<%= new_user_url %>Go back to sign in</a> -->
<a class = 'button' href=<%= new_session_url %> >Go to Sign-in</a>

<p>
  Email: <%= current_user.email %>
</p>